name: Revisión de código bff

on:
    push:
      branches: [main]
      paths:
        - 'bff/**'
    workflow_dispatch: # Agrega este desencadenante
    pull_request:
      branches: [main]
      paths:
        - 'bff/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Clona el repositorio para que los trabajos puedan acceder al código.
      - name: Configurar Python e instalar Pylint # Combinamos la configuración y la instalación
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Ejecutar Pylint
        run: |
          pylint ./bff/src

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python e instalar Black # Combinamos la configuración y la instalación
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Ejecutar Black
        run: |
          black --check ./bff/src

#  test:
#    needs: setup
#    runs-on: ubuntu-latest
#    steps:
#      - name: Ejecutar pruebas unitarias
#        run: |
#          python -m unittest discover -s ./book_service/tests

  build-and-push-docker: # Define el trabajo para construir y subir la imagen Docker.
#   needs: test # Indica que este trabajo depende del trabajo 'test'.
    runs-on: ubuntu-latest # Especifica que el trabajo se ejecutará en una máquina virtual Ubuntu.
    steps: # Define los pasos para construir y subir la imagen.
        - uses: actions/checkout@v4 # Clona el repositorio para acceder al Dockerfile y al código.
        - name: Depurar nombre del repositorio
          run: echo "Nombre del repositorio:" ${{ github.repository }} 
        - name: Iniciar sesión en GitHub Container Registry # Inicia sesión en el registro de contenedores de GitHub.
          run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin # Utiliza un secreto para la autenticación.
        - name: Construir y etiquetar la imagen Docker # Construye la imagen Docker y la etiqueta.
          run: docker build -t ghcr.io/${{ github.repository }}/biblioteca-bff:latest -f ./bff/Dockerfile . # Utiliza el Dockerfile en 'book_service' y etiqueta la imagen.
        - name: Subir la imagen Docker a GitHub Container Registry # Sube la imagen Docker al registro.
          run: docker push ghcr.io/${{ github.repository }}/biblioteca-bff:latest # Envía la imagen al registro de contenedores.

  set-package-visibility:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Establecer visibilidad del paquete como pública
        env:
          GH_TOKEN: ${{ secrets.CR_PAT }}
        run: |
          curl -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GH_TOKEN" \
          https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ github.repository }}/biblioteca-bff/visibility \
          -d '{"visibility":"public"}'